<?php
$SYS_WARN_MSG = array(

	'not_all_mandatory' => 'No todos los campos obligatorios están llenos de',
	'action_wrong' => 'Parámetro Action está mal',
	'password_notconfirm' => 'Contraseña y Confirmar contraseña son diferentes',
	'password_missed' => 'Contraseña o confirme la contraseña se pierden',
	'modul_notfound' => 'Módulo está desactivado',
	'dateformat_wrong' => 'El formato de fecha es incorrecto',
	'format_wrong' => 'El formato es incorrecto',
	'no_results' => 'No se han encontrado resultados',
	'session_old' => 'Your session is older than 5 hours. ',
	'email_invalid' => 'Formato de correo electrónico incorrecta',
	'email_sent' => 'Correo electrónico enviado',
	'email_notsent' => 'Email was not sent',
	'email_earlysent' => 'Email was already sent',
	'email_rejected' => 'Email is deleted',
	'status_updated' => 'Status updated',
	'ext_notvalid' => 'Supported extentions are jpg, gif and png',
	'cleanup' => 'Cleanup is successfull',

	'your_login' => 'Introduzca su usuario y contraseña, a continuación, pulse Entrar',
	'wrong_psw' => 'La contraseña es incorrecta',
	'wrong_nick' => 'Nombre de acceso es incorrecto',
	'user_locked' => 'El usuario está bloqueada 20 second',
	'not_auth' => 'El usuario no está autorizado',
	'exists' => 'Entidad ya existe',

	'created' => 'Se crea contenido',
	'u_created' => 'Se crea Usuario',
	'notcreated' => 'No se puede insertar en la base de datos',
	'deleted' => 'Contenido se borra',
	'u_deleted' => 'El usuario se elimina',
	'p_deleted' => 'Perfil se elimina',
	'r_deleted' => 'El papel se elimina',
	'notdeleted' => 'No se puede borrar de la base de datos',
	'notsingle' => 'Entidad cuenta con los elementos sub',
	'updated' => 'El contenido se actualiza',
	'notupdated' => 'No se puede actualizar la base de datos',
	'conf_updated' => 'Las propiedades se actualizan',
	'parent_same' => 'Padres e hijos son los mismos',
	'empty' => 'El contenido está vacío',
	'no_select' => 'Consulta falta',
	'filter_a' => 'Se aplica Filtrar',

	'f_created' => 'Se crea Archivo',
	'f_notcreated' => 'El nombre no es único o permisos se les niega',
	'f_updated' => 'El archivo se actualiza',
	'f_notupdated' => 'Permiso para presentar negado',
	'f_uploaded' => 'El archivo está subido',
	'f_notuploaded' => 'Nombre de archivo no es única o permiso denegado',
	'f_copied' => 'Archivo se copia',
	'f_notcopied' => 'Los permisos se negaron',
	'f_downloaded' => 'Descargado',
	'f_notdownloaded' => 'Los permisos se negaron',
	'f_name_accept' => 'Nombre debe contener sólo A-Z, a-z, 0-9, -, _',
	'f_name_empty' => 'Nombre está vacío',
	'f_name_ext' => 'Solo se admiten tipos jpg, jpeg, png, gif, webm, mp4, mpg, mov, mp3',
	'f_deleted' => 'El archivo se borra',
	'f_notdeleted' => 'Los permisos se negaron',
	'f_special_warn' => 'El código contiene caracteres &amp;#, que se puede guardar de forma incorrecta',
	'f_exist' => 'El archivo ya está existir',
	'd_created' => 'Se crea la carpeta',
	'd_notcreated' => 'El nombre no es único o permisos se les niega',
	'd_deleted' => 'Carpeta eliminada',
	'd_empty' => 'Carpeta está vacía',
	'd_notempty' => 'La carpeta no está vacía',
	'a_updated' => 'Atributo se actualiza',
	'a_notupdated' => 'Los permisos se negaron',
	'a_wrong' => 'Atributo está mal definido',

	'up' => 'Ascendente',
	'down' => 'Descendente',
	'nick' => 'Nombre',
	'status' => 'Estado',
	'title' => 'Título',
	'role' => 'Sumisión',
	'date' => 'Fecha',
	'webpage' => 'Web page',

	'content_default' => '<p class="title1">Title</p><p>Content</p>',

	'dump_created' => 'Los datos extraídos con éxito',
	'dump_updated' =>  'DB actualizado correctamente',
	'dump_updated_with' =>  'DB actualizado, resultado es con advertencias',
	'dump_nocontent' => 'Contenido es olvidada',
	'sql_ok' => 'SQL ejecutado',

	'mr_id' => 'Señor', 'mr_ref' => 'Estimado Señor',
	'ms_id' => 'Señora', 'ms_ref' => 'Estimado Señora'
);


?>
