<?php
$SYS_WARN_MSG = array(

	'not_all_mandatory' => 'Nicht alle Pflichtfelder sind ausgef&uuml;llt',
	'action_wrong' => 'Parameter Action ist unbekannt',
	'password_notconfirm' => 'Passwort und Passwort zum Wiederholen sind anders',
	'password_missed' => 'Passwort oder Passwort zum Wiederholen fehlt',
	'modul_notfound' => 'Modul ist inaktiv', 
	'dateformat_wrong' => 'Datumsformat ist falsch',
	'format_wrong' => 'Format ist falsch',
	'no_results' => 'Keine Treffer',
	'session_old' => 'Ihre Session ist &auml;lter als 5 Stunden. ',
	'email_invalid' => 'E-Mail-Adresse ist falsch',
	'email_sent' => 'E-Mail abgeschickt',
	'email_notsent' => 'E-Mail konnte nicht abgeschickt werden',
	'email_earlysent' => 'E-Mail wurde schon ein Mal abgeschickt',
	'email_rejected' => 'E-Mail-Adresse ist gelöscht',
	'status_updated' => 'Status aktualisiert',
	'ext_notvalid' => 'Unterst&uuml;tzt werden nur jpg, gif und png',
	'cleanup' => 'Aufger&auml;mt',

	'your_login' => 'Geben Sie Ihren Benutzernamen und das Passwort ein',
	'wrong_psw' => 'Passwort ist falsch',
	'wrong_nick' => 'Loginname ist falsch',
	'user_locked' => 'Benutzer ist für 20 Sekunden gesperrt',
	'not_auth' => 'Benutzer ist nicht angemeldet',
	'exists' => 'Exitiert schon',

	'created' => 'Erfolgreich erstellt',
	'u_created' => 'Benutzer wurde erstellt',
	'notcreated' => 'Kann nicht in die Datenbank einf&uuml;gen',
	'deleted' => 'Erfolgreich gel&ouml;scht',
	'u_deleted' => 'Benutzer wurde gel&ouml;scht',
	'p_deleted' => 'Profil wurde gel&ouml;scht',
	'r_deleted' => 'Role wurde gel&ouml;scht',
	'notdeleted' => 'Kann nicht aus der Datenbank l&ouml;schen',
	'notsingle' => 'Es gibt die Abh&auml;ngigkeiten',
	'updated' => 'Erfolgreich aktualisiert',
	'notupdated' => 'Kann nicht in der Datenbank aktualisieren',
	'conf_updated' => 'Einstellungen wurden aktualisiert',
	'parent_same' => 'Haupt- und Unterobjekt ist identisch',
	'empty' => 'Inhalt ist leer',
	'no_select' => 'Keine Abfrage gefunden',
	'filter_a' => 'Filter ist angewendet',

	'f_created' => 'Datei wurde erstellt',
	'f_notcreated' => 'Name ist vorhanden oder die Zugriffsberechtigungen fehlen',
	'f_updated' => 'Datei wurde aktualisiert',
	'f_notupdated' => 'Zugriffsberechtigungen reichen nicht',
	'f_uploaded' => 'Datei wurde hochgeladen',
	'f_notuploaded' => 'Datei ist schon vorhanden oder Zugriffsberechtigungen reichen nicht',
	'f_copied' => 'Datei wurde kopiert',
	'f_notcopied' => 'Zugriffsberechtigungen reichen nicht',
	'f_downloaded' => 'Datei wurde heruntergeladen',
	'f_notdownloaded' => 'Zugriffsberechtigungen reichen nicht',
	'f_name_accept' => 'Erlaubt sind nur A-Z, a-z, 0-9, -, _',
	'f_name_empty' => 'Name ist leer',
	'f_name_ext' => 'Unterst&uuml;tzt sind nur jpg, jpeg, png, gif, webm, mp4, mpg, mov, mp3',
	'f_deleted' => 'Datei wurde gel&ouml;scht',
	'f_notdeleted' => 'Zugriffsberechtigungen reichen nicht',
	'f_special_warn' => 'Achtung. Der Code enthält Symbol &amp;#, der falsch gespeichert werden kann',
	'f_exist' => 'Datei ist vorhanden',
	'd_created' => 'Verzeichnis wurde erstellt',
	'd_notcreated' => 'Name ist vorhanden oder die Zugriffsberechtigungen fehlen',
	'd_deleted' => 'Verzeichnis wurde gel&ouml;scht',
	'd_empty' => 'Verzeichnis ist leer',
	'd_notempty' => 'Verzeichnis ist nicht leer',
	'a_updated' => 'Attribut wurde aktualisiert',
	'a_notupdated' => 'Zugriffsberechtigungen reichen nicht',
	'a_wrong' => 'Attribut ist falsch definiert',

	'up' => 'aufsteigend',
	'down' => 'absteigend',
	'nick' => 'Login',
	'status' => 'Status',
	'title' => 'Titel',
	'role' => 'Vorlage',
	'date' => 'Datum',
	'webpage' => 'Webseite',

	'content_default' => '<p class="title1">Titel</p><p>Inhalt</p>',

	'dump_created' => 'Daten wurden erfolgreich extrahiert',
	'dump_updated' =>  'Datenbank wurde erfolgreich aktualisiert',
	'dump_updated_with' =>  'Datenbank wurde aktualisiert, es gibt die Fehler',
	'dump_nocontent' => 'Inhalt ist leer',
	'sql_ok' => 'Abfrage ausgef&uuml;hrt',

	'mr_id' => 'Herr', 'mr_ref' => 'Sehr geehrter Herr',
	'ms_id' => 'Frau', 'ms_ref' => 'Sehr geehrte Frau'
);


?>
