<?php
$SYS_WARN_MSG = array(

	'not_all_mandatory' => 'Not all mandatory fields are filled in',
	'action_wrong' => 'Action parameter is wrong',
	'password_notconfirm' => 'Password and Password Confirm are different',
	'password_missed' => 'Password or confirm password are missed',
	'modul_notfound' => 'Module is disabled',
	'dateformat_wrong' => 'Date format is wrong',
	'format_wrong' => 'Format is wrong',
	'no_results' => 'No results have been found',
	'session_old' => 'Your session is older than 5 hours. ',
	'email_invalid' => 'Email format is wrong',
	'email_sent' => 'Email sent',
	'email_notsent' => 'Email was not sent',
	'email_earlysent' => 'Email was already sent',
	'email_rejected' => 'Email is deleted',
	'status_updated' => 'Status updated',
	'ext_notvalid' => 'Supported extentions are jpg, gif and png',
	'cleanup' => 'Cleanup is successfull',

	'your_login' => 'Enter your login and password, then press Login',
	'wrong_psw' => 'Password is incorrect',
	'wrong_nick' => 'Login name is incorrect',
	'user_locked' => 'User is locked for 20 seconds',
	'not_auth' => 'User is not authorized',
	'exists' => 'Entity already exist',

	'created' => 'Content is created',
	'u_created' => 'User is created',
	'notcreated' => 'Can not insert into data base',
	'deleted' => 'Content is deleted',
	'u_deleted' => 'User  is deleted',
	'p_deleted' => 'Profile is deleted',
	'r_deleted' => 'Role is deleted',
	'notdeleted' => 'Can not delete from data base',
	'notsingle' => 'Entity has the sub items',
	'updated' => 'Content is updated',
	'notupdated' => 'Can not update the data base',
	'conf_updated' => 'Properties are updated',
	'parent_same' => 'Parent and child are the same',
	'empty' => 'Content is empty',
	'no_select' => 'Query is missing',
	'filter_a' => 'Filter is applied',

	'f_created' => 'File is created',
	'f_notcreated' => 'Name is not unique or permissions are denied',
	'f_updated' => 'File is updated',
	'f_notupdated' => 'Permission to file denied',
	'f_uploaded' => 'File is uploaded',
	'f_notuploaded' => 'File name is not unique or permission denied',
	'f_copied' => 'File is copied',
	'f_notcopied' => 'Permissions are denied',
	'f_downloaded' => 'Downloaded',
	'f_notdownloaded' => 'Permissions are denied',
	'f_name_accept' => 'Name should contain only A-Z, a-z, 0-9, -, _',
	'f_name_empty' => 'Name is empty',
	'f_name_ext' => 'Supported types are only jpg, jpeg, png, gif, webm, mp4, mpg, mov, mp3',
	'f_deleted' => 'File is deleted',
	'f_notdeleted' => 'Permissions are denied',
	'f_special_warn' => 'Attention. The code contains character &amp;#, which can be saved incorrectly',
	'f_exist' => 'File already is exist',
	'd_created' => 'Folder is created',
	'd_notcreated' => 'Name is not unique or permissions are denied',
	'd_deleted' => 'Folder deleted',
	'd_empty' => 'Folder is empty',
	'd_notempty' => 'Folder is not empty',
	'a_updated' => 'Attribute is updated',
	'a_notupdated' => 'Permissions are denied',
	'a_wrong' => 'Attribute is wrong defined',

	'up' => 'Ascendic',
	'down' => 'Descendic',
	'nick' => 'Nick',
	'status' => 'Status',
	'title' => 'Title',
	'role' => 'Role',
	'date' => 'Date',
	'webpage' => 'Web page',

	'content_default' => '<p class="title1">Title</p><p>Content</p>',

	'dump_created' => 'Data extracted successfully',
	'dump_updated' =>  'DB updated successfully',
	'dump_updated_with' =>  'DB updated, result is with warnings',
	'dump_nocontent' => 'Content is missed',
	'sql_ok' => 'SQL executed',

	'mr_id' => 'Mr', 'mr_ref' => 'Dear Mr',
	'ms_id' => 'Ms', 'ms_ref' => 'Dear Ms'
);


?>
